FROM mcr.microsoft.com/devcontainers/base:debian
RUN apt-get update && apt-get install -y --no-install-recommends build-essential binutils-arm-none-eabi libpng-dev python3 libmgba-dev ca-certificates && rm -rf /var/lib/apt/lists/*
