#!/usr/bin/env python3
"""Write worker/src/maps.ts: "group.num" -> readable map name, from the decomp's
generated include/constants/map_groups.h. Rerun after map changes (make setup/build first)."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / '.cache/pokefirered/include/constants/map_groups.h'
OUT = ROOT / 'worker/src/maps.ts'

def pretty(const: str) -> str:
    words = const.removeprefix('MAP_').split('_')
    fix = lambda w: w if re.fullmatch(r'\d+F|B\d+F|\d+R', w) else re.sub(r'(\D)(\d)', r'\1 \2', w.capitalize())
    return ' '.join(fix(w) for w in words)

entries = {f'{g}.{n}': pretty(c) for c, n, g in re.findall(r'#define (MAP_\w+)\s+\((\d+) \| \((\d+) << 8\)\)', SRC.read_text())}
lines = [f'  "{k}": "{v}",' for k, v in entries.items()]
OUT.write_text('// Generated by scripts/map_names.py from pokefirered include/constants/map_groups.h. Do not edit.\n'
               'export const MAP_NAMES: Record<string, string> = {\n' + '\n'.join(lines) + '\n}\n')
print(f'{len(entries)} maps -> {OUT.relative_to(ROOT)}')
