// Write notes/moves.md from the shared rules (rules/): types' two faces, move families, all moves.
//   node battle/export.mjs ../notes/moves.md
import { writeFileSync } from 'node:fs'
import { EXAMPLE_BYTES, FAMILIES, FORMATS, HINTS, MOVES, example, show } from '../../rules/index.mjs'

const [md] = process.argv.slice(2)
const byType = {}
for (const m of MOVES) (byType[m.type] ??= []).push(m)
const fmtOf = t => FORMATS[t.toUpperCase()]
if (md) writeFileSync(md, [
  '# Types and moves (generated 2026-10-08)', '',
  'Source of truth: `rules/moves.mjs` (names, families, specs, reference answers) and `rules/formats.mjs` (each type\'s data format and Pokédex reader). Generated by `models/battle/export.mjs`.', '',
  '## The spine',
  '- every Pokémon is a system; its type is the kind of system; a move is a program of the move\'s type run against the target\'s system',
  '- defender face: the target type decides the format the move\'s function receives · attacker face: every move\'s code belongs to its type\'s family',
  '- the Pokémon writes `function <fn>(data)`; the game runs it on the target\'s data; the right answer hits, anything else misses (the text box says why); FireRed does the rest',
  '- positions count from 0; ties → the first; "rounded down" = floor', '',
  '## Types: two faces', '', `Example numbers: [${EXAMPLE_BYTES.join(', ')}]`, '',
  '| Type | Data arrives as | Example | Pokédex reader | Its moves… |', '|---|---|---|---|---|',
  ...Object.keys(FAMILIES).filter(t => t !== 'Mystery').map(t => `| ${t} | ${fmtOf(t)?.note ?? 'a plain list'} | \`${fmtOf(t) ? show(example(t.toUpperCase())) : '[…]'}\` | \`${HINTS[t.toUpperCase()] ?? 'const bytes = data'}\` | ${FAMILIES[t]} |`), '',
  `## Moves (${MOVES.length})`, '', 'S = a starter learns it before Brock · K = FireRed name kept', '',
  ...Object.keys(FAMILIES).flatMap(t => byType[t] ? [`### ${t}: ${FAMILIES[t]}`, '', '| Move | Was | Power/acc | Effect | The code computes | |', '|---|---|---|---|---|---|',
    ...byType[t].map(m => `| ${m.name} | ${m.firered} | ${m.power}/${m.acc} | ${m.effect} | ${m.spec} | ${[m.starter && 'S', m.kept && 'K'].filter(Boolean).join(' ')} |`), ''] : []),
].join('\n'))
